'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace TheAPIWeb


	Partial Public Class _Default

		''' <summary>
		''' WebSample control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected WebSample As Global.System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' Label1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Label1 As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' txtDocNo control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected txtDocNo As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' btnView control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected btnView As Global.System.Web.UI.WebControls.Button
	End Class
End Namespace
